### ISSUE TITLE
missing alignment in linker script

### ISSUE THREAD

**Issue by prof7bit** [0xc0170/kinetis_klxx_gcc#1]
Hello,

thank you for these files, they were incredibly helpful for me already!

But there is a problem: It only happens when using -nostartfiles or -nostdlib.

I began experimenting with the linker options and leaving away the gcc generated standard startup code and providing my own implementation of _start instead. This went fine until I had some global variables to initialize with the flash_to_ram loop. It hard-faulted on the very first ldr instruction in the freescale provided startup_xxx.s file.

Upon closer inspection of what has happened I observed that my data was not aligned in the flash anymore and according to what I have read this will result in a hardfault.

This is how the last 4 bytes look when using the original linker script (they should be an unsigned long number 42), this longword is not aligned at 4-byte boundary:

![_align_wrong](https://cloud.githubusercontent.com/assets/1401589/6333813/758f0898-bb90-11e4-82df-ea2d6d3c88c5.png)

and this is how it looked after throwing in another ALIGN(4) into the linker script at the position I thought should be correct (see patch below), now it is aligned. This is also what somehow magically happens when _not_ using the -nostartfiles or -nostdlib options in gcc, it seems gcc will change these symbos on its own by default, so the bug in the original linker script had no effect at all with standard compilation options.

![_align_correct](https://cloud.githubusercontent.com/assets/1401589/6333832/9a1c95f4-bb90-11e4-9d3e-edb50816e333.png)

Now here is what I did: 

I don't know much about linker scripts, this is just what I intuitively believed to be correct, I just inserted another ALIGN(4) in front of the __exidx_end symbol:

```
diff -u cmsis/MKL05Z4/MKL05Z4_old.ld cmsis/MKL05Z4/MKL05Z4.ld 
--- cmsis/MKL05Z4/MKL05Z4_old.ld        2015-02-23 18:40:22.734195960 +0100
+++ cmsis/MKL05Z4/MKL05Z4.ld    2015-02-23 18:57:31.905617614 +0100
@@ -97,6 +97,8 @@
     {
         *(.ARM.exidx* .gnu.linkonce.armexidx.*)
     } > FLASH
+    
+    . = ALIGN(4);
     __exidx_end = .;

     __etext = .;

```

Now the data is aligned properly.

**Comment by 0xc0170** [comment]
Hi, thanks for reporting. Looks like I missed the alignment for vtable and data. Will you send the pull request, all the ld need to be fixed.

I propose this:

```
     . = ALIGN(4); // // <--- your addition
     __etext = .;
    .data : AT (__etext)
    {
         . = ALIGN(4); // <-----added also
        __data_start__ = .;
        *(vtable)
        *(.data*)

        . = ALIGN(4);
        /* preinit data */
        PROVIDE_HIDDEN (__preinit_array_start = .);
        KEEP(*(.preinit_array))
        PROVIDE_HIDDEN (__preinit_array_end = .);

        . = ALIGN(4);
        /* init data */
        PROVIDE_HIDDEN (__init_array_start = .);
        KEEP(*(SORT(.init_array.*)))
        KEEP(*(.init_array))
        PROVIDE_HIDDEN (__init_array_end = .);


        . = ALIGN(4);
        /* finit data */
        PROVIDE_HIDDEN (__fini_array_start = .);
        KEEP(*(SORT(.fini_array.*)))
        KEEP(*(.fini_array))
        PROVIDE_HIDDEN (__fini_array_end = .);

        . = ALIGN(4);
        /* All data end */
        __data_end__ = .;

    } > RAM
```

Which follows what's in there, should have the same result as yours above. What do you think?

**Comment by 0xc0170** [comment]
I sent #2 , please review and let me know if that fixes this, I'll merge it.

Thanks for taking time to report this bug.

**Comment by 0xc0170** [comment]
#2 merged
